module-name: keda-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/keda-manager:v20230719-22acef2b
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda:2.11.1
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-admission-webhooks:2.11.1
  - europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/kedacore/keda-metrics-apiserver:2.11.1
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
