apiVersion: operator.kyma-project.io/v1alpha1
kind: Keda
metadata:
  name: default
spec:
  logging:
    operator:
      level: "info"
  resources:
    operator:
      limits:
        cpu: "800m"
        memory: "800Mi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    metricServer:
      limits:
        cpu: "800m"
        memory: "800Mi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    admissionWebhook:
      limits:
        cpu: "800m"
        memory: "800Mi"
      requests:
        cpu: "50m"
        memory: "100Mi"