apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: request-generator
  name: request-generator
  namespace: keda-dynatrace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-generator
  template:
    metadata:
      labels:
        app: request-generator
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
         - "/bin/sh"
         - "-c"
         - "--"
        args:
          - "while true; do sleep 0.5; wget -q -O- https://httpbin.keda-dynatrace.svc.cluster.local/get > /dev/null ; done"
