details: |-
  {
    "header": [],
    "body": [
      {
        "name": "Summary",
        "widget": "Panel",
        "children": [
          {
            "name": "cooldownPeriod",
            "source": "spec.cooldownPeriod"
          },
          {
            "name": "idleReplicaCount",
            "source": "spec.idleReplicaCount"
          },
          {
            "name": "maxReplicaCount",
            "source": "spec.maxReplicaCount"
          },
          {
            "name": "minReplicaCount",
            "source": "spec.minReplicaCount"
          },
          {
            "name": "pollingInterval",
            "source": "spec.pollingInterval"
          },
          {
            "name": "ScaleTargetKind",
            "source": "status.scaleTargetKind"
          },
          {
            "name": "ScaleTargetName",
            "source": "spec.scaleTargetRef.name"
          },
          {
            "name": "Min",
            "source": "spec.minReplicaCount"
          },
          {
            "name": "Max",
            "source": "spec.maxReplicaCount"
          },
          {
            "name": "Triggers",
            "source": "spec.triggers[*].type"
          },
          {
            "name": "Authentication",
            "source": "spec.triggers[*].authenticationRef.name"
          },
          {
            "name": "Ready",
            "source": "status.conditions[?(@.type==\"Ready\")].status"
          },
          {
            "name": "Active",
            "source": "status.conditions[?(@.type==\"Active\")].status"
          },
          {
            "name": "Fallback",
            "source": "status.conditions[?(@.type==\"Fallback\")].status"
          },
          {
            "name": "Age",
            "source": "metadata.creationTimestamp"
          }
        ]
      },
      {
        "source": "spec",
        "widget": "CodeViewer"
      }
    ]
  }
form: |-
  [
    {
      "simple": true,
      "path": "spec.cooldownPeriod",
      "required": false
    },
    {
      "simple": true,
      "path": "spec.idleReplicaCount",
      "required": false
    },
    {
      "simple": true,
      "path": "spec.maxReplicaCount",
      "required": false
    },
    {
      "simple": true,
      "path": "spec.minReplicaCount",
      "required": false
    },
    {
      "simple": true,
      "path": "spec.pollingInterval",
      "required": false
    }
  ]
general: |-
  {
    "resource": {
      "kind": "ScaledObject",
      "group": "keda.sh",
      "version": "v1alpha1"
    },
    "name": "Scaled Objects",
    "category": "Workloads",
    "urlPath": "scaledobjects",
    "scope": "namespace"
  }
list: |-
  [
    {
      "name": "ScaleTargetKind",
      "source": "status.scaleTargetKind"
    },
    {
      "name": "ScaleTargetName",
      "source": "spec.scaleTargetRef.name"
    },
    {
      "name": "Min",
      "source": "spec.minReplicaCount"
    },
    {
      "name": "Max",
      "source": "spec.maxReplicaCount"
    },
    {
      "name": "Triggers",
      "source": "spec.triggers[*].type"
    },
    {
      "name": "Ready",
      "source": "status.conditions[?(@.type==\"Ready\")].status"
    },
    {
      "name": "Active",
      "source": "status.conditions[?(@.type==\"Active\")].status"
    },
    {
      "name": "Age",
      "source": "metadata.creationTimestamp"
    }
  ]
translations: |-
  {
    "en": {
      "metadata.annotations": "Annotations",
      "metadata.labels": "Labels",
      "metadata.creationTimestamp": "Created at"
    }
  }

