name: integration tests

on:
  workflow_call:
    inputs:
      image:
        description: 'The image to test'
        required: true
        type: string

jobs:
  integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: make -C hack/ci integration-test-on-cluster
        env:
          IMG: ${{ inputs.image }}

  btp-integration-tests:
    if: ${{ !startsWith(github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kyma
        with:
          path: "/usr/local/bin"
      - uses: ./.github/actions/setup-terraform
      - name: Create btp account with kyma enabled
        run: |
          . ./set-tf-envs.sh
          terraform -chdir=../tf init
          terraform -chdir=../tf apply -auto-approve
          echo "SUBACC_ID=$(terraform -chdir=../tf output -raw subaccount_id)" >> $GITHUB_ENV
        env:
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_NEW_SUBACCOUNT_NAME: keda-manager-test-${{ github.sha }}-${{ github.run_attempt }}

      - name: Generate access
        run: |
          sudo ln -sf bash /bin/sh
          . ./set-tf-envs.sh
          mkdir -p tmp
          CLUSTERROLE=cluster-admin make service-account-kubeconfig
        env:
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}

      - name: Run Keda Manager's integration test
        run: |
          KUBECONFIG=/tmp/sa-kubeconfig.yaml make -C ../../../hack/ci integration-test-on-cluster

      - uses: ./.github/actions/setup-btp
        if: always()
        with:
          path: "/usr/local/bin"

      - name: Force delete btp account
        if: always()
        run: |
          . ./set-tf-envs.sh
          btp login --url $TF_VAR_BTP_BACKEND_URL --user $TF_VAR_BTP_BOT_USER --password $TF_VAR_BTP_BOT_PASSWORD --idp $TF_VAR_BTP_CUSTOM_IAS_TENANT --subdomain $TF_VAR_BTP_GLOBAL_ACCOUNT
          btp delete accounts/subaccount ${SUBACC_ID} --global-account ${TF_VAR_BTP_GLOBAL_ACCOUNT} --force-delete true --confirm true
        env:
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
