name: DevOps Insight

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DevOps-Insights
        run: |
          curl -O https://int.repositories.cloud.sap/artifactory/devops-insights-generic/bin/latest/devops-insights.linux.amd64
          chmod +x ./devops-insights.linux.amd64
      - name: Dora
        run: |
          ./devops-insights.linux.amd64 \
            --artifactVersion=${{ github.event.inputs.name  }} \
            --devOpsInsightsToken=${{ secrets.ACCESS_TOKEN_HYPERSPACE_GITHUB }} \
            --identifier=keda-manager \
            --commitID=${{ github.sha }} \
            --deploymentTarget=development \
            --gitInstance=github.com \
            --gitOrganization=kyma-project \
            --gitRepository=keda-manager \
            --githubToken=${{ secrets.GITHUB_TOKEN }} \
            --verbose